name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      # Pinnato all'hash di commit specifico invece di @v4
      - uses: actions/checkout@a44f66a018a13919c62a87a552b75de08e0aee0f
        with:
          fetch-depth: 0
    
      # Pinnato all'hash di commit specifico invece di @v5
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: '1.22'
    
      - name: Run tests and generate coverage report
        run: go test ./... -coverprofile=coverage.out
    
      # Pinnato all'hash di commit specifico invece di @master
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@46542565922c06e1669527f394018f2762a106f3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=giannidg21
            -Dsonar.projectKey=GianniDG21_keeper